/**
 * @file Core1.c
 * @generated by CPrinter
 * @date Mon Jun 18 17:13:14 CEST 2018
 *
 * Code generated for processing element Core1 (ID=1).
 */

#define _GNU_SOURCE
#include <pthread.h>

// PE specific includes
#include "x86.h"

// application dependent includes
#include "preesm.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_output__Sobel___1;  // explode_Split_output > Sobel_1 size:= 26048*char defined in Core0
extern uchar *const output_26048__input__0;  // explode_Split_output_output_26048 > Sobel_1_input size:= 26048*uchar defined in Core0
extern uchar *const output__input_26048__0;  // Sobel_1_output > implode_Merge_input_input_26048 size:= 26048*uchar defined in Core0
extern char *const Sobel_1__implode_Merge_input__0;  // Sobel_1 > implode_Merge_input size:= 26048*char defined in Core0
extern char *const explode_Split_output__Sobel___3;  // explode_Split_output > Sobel_3 size:= 26048*char defined in Core0
extern uchar *const output_78144__input__0;  // explode_Split_output_output_78144 > Sobel_3_input size:= 26048*uchar defined in Core0
extern uchar *const output__input_78144__0;  // Sobel_3_output > implode_Merge_input_input_78144 size:= 26048*uchar defined in Core0
extern char *const Sobel_3__implode_Merge_input__0;  // Sobel_3 > implode_Merge_input size:= 26048*char defined in Core0

// Core Global Definitions

void *computationThread_Core1(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core0 > Core1: explode_Split_output__Sobel___1
		receiveEnd(0, 1); // Core0 > Core1: explode_Split_output__Sobel___1
//		sobel(352/*width*/,74/*height*/,output_26048__input__0,output__input_26048__0); // Sobel_1
		sobel_filter1(output_26048__input__0,output__input_26048__0,74/*height*/); // Sobel_1
		sendStart(1, 0); // Core1 > Core0: Sobel_1__implode_Merge_input__0
		sendEnd(); // Core1 > Core0: Sobel_1__implode_Merge_input__0
		receiveStart(); // Core0 > Core1: explode_Split_output__Sobel___3
		receiveEnd(0, 1); // Core0 > Core1: explode_Split_output__Sobel___3
//		sobel(352/*width*/,74/*height*/,output_78144__input__0,output__input_78144__0); // Sobel_3
		sobel_filter3(output_78144__input__0,output__input_78144__0,74/*height*/); // Sobel_3
		sendStart(1, 0); // Core1 > Core0: Sobel_3__implode_Merge_input__0
		sendEnd(); // Core1 > Core0: Sobel_3__implode_Merge_input__0
	}
	return NULL;
}

