/**
 * @file main.c
 * @generated by CPrinter
 * @date Mon Jun 18 17:13:14 CEST 2018
 *
 */

#define _GNU_SOURCE
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#include <pthread.h>
#include <stdio.h>

#define _PREESM_NBTHREADS_ 2

// application dependent includes
#include "preesm.h"

// Declare computation thread functions
void *computationThread_Core0(void *arg);
void *computationThread_Core1(void *arg);

pthread_barrier_t iter_barrier;
int stopThreads;


unsigned int launch(unsigned int core_id, pthread_t * thread, void *(*start_routine) (void *)) {
	// check CPU id is valid
	// init cpuset struct
	cpu_set_t cpuset;
	CPU_ZERO(&cpuset);
	CPU_SET(core_id, &cpuset);
	// init pthread attributes with affinity
	pthread_attr_t attr;
	pthread_attr_init(&attr);

#ifdef _WIN32
	SYSTEM_INFO sysinfo;
	GetSystemInfo(&sysinfo);
	unsigned int numCPU = sysinfo.dwNumberOfProcessors;
#else
	unsigned int numCPU = sysconf(_SC_NPROCESSORS_ONLN);
#endif
	if (core_id >= numCPU) {
		// leave attribute uninitialized
		printf("** Warning: thread %d will not be set with specific core affinity \n   due to the lack of available dedicated cores.\n",core_id);
	} else {
		pthread_attr_setaffinity_np(&attr, sizeof(cpuset), &cpuset);
	}

	// create thread
	pthread_create(thread, &attr, start_routine, NULL);
	return 0;
}


int main(void) {
	// Declaring thread pointers
	pthread_t coreThreads[_PREESM_NBTHREADS_];
	void *(*coreThreadComputations[_PREESM_NBTHREADS_])(void *) = {
		&computationThread_Core0, &computationThread_Core1
	};

#ifdef VERBOSE
	printf("Launched main\n");
#endif

	// Creating a synchronization barrier
	stopThreads = 0;
	pthread_barrier_init(&iter_barrier, NULL, _PREESM_NBTHREADS_);

	communicationInit();

	// Creating threads
	for (int i = 0; i < _PREESM_NBTHREADS_; i++) {
		if(launch(i,&coreThreads[i],coreThreadComputations[i])) {
			printf("Error: could not launch thread %d\n",i);
			return 1;
		}
	}

	// Waiting for thread terminations
	for (int i = 0; i < _PREESM_NBTHREADS_; i++) {
		pthread_join(coreThreads[i], NULL);
	}
	printf("END\n");

	return 0;
}

