/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Mon Jun 18 17:13:14 CEST 2018
 *
 * Code generated for processing element Core0 (ID=0).
 */

#define _GNU_SOURCE
#include <pthread.h>

// PE specific includes
#include "x86.h"

// application dependent includes
#include "preesm.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;

// Core Global Definitions
char Shared[670208]; //  size:= 670208*char
char *const Read_YUV__display__0 = (char*) (Shared+0);  // Read_YUV > display size:= 50688*char
char *const Read_YUV__Split__0 = (char*) (Shared+50688);  // Read_YUV > Split size:= 101376*char
char *const Split__explode_Split_output__0 = (char*) (Shared+152064);  // Split > explode_Split_output size:= 104192*char
char *const explode_Split_output__Sobel___0 = (char*) (Shared+256256);  // explode_Split_output > Sobel_0 size:= 26048*char
char *const explode_Split_output__Sobel___1 = (char*) (Shared+282304);  // explode_Split_output > Sobel_1 size:= 26048*char
char *const explode_Split_output__Sobel___2 = (char*) (Shared+308352);  // explode_Split_output > Sobel_2 size:= 26048*char
char *const explode_Split_output__Sobel___3 = (char*) (Shared+334400);  // explode_Split_output > Sobel_3 size:= 26048*char
char *const Sobel_0__implode_Merge_input__0 = (char*) (Shared+360448);  // Sobel_0 > implode_Merge_input size:= 26048*char
char *const Sobel_2__implode_Merge_input__0 = (char*) (Shared+386496);  // Sobel_2 > implode_Merge_input size:= 26048*char
char *const Sobel_1__implode_Merge_input__0 = (char*) (Shared+412544);  // Sobel_1 > implode_Merge_input size:= 26048*char
char *const Sobel_3__implode_Merge_input__0 = (char*) (Shared+438592);  // Sobel_3 > implode_Merge_input size:= 26048*char
char *const implode_Merge_input__Merge__0 = (char*) (Shared+464640);  // implode_Merge_input > Merge size:= 104192*char
char *const Merge__display__0 = (char*) (Shared+568832);  // Merge > display size:= 101376*char
uchar *const u__u__0 = (uchar*) (Shared+0);  // Read_YUV_u > display_u size:= 25344*uchar
uchar *const v__v__0 = (uchar*) (Shared+25344);  // Read_YUV_v > display_v size:= 25344*uchar
uchar *const y__input__0 = (uchar*) (Shared+50688);  // Read_YUV_y > Split_input size:= 101376*uchar
uchar *const output__input__0 = (uchar*) (Shared+152064);  // Split_output > explode_Split_output_input size:= 104192*uchar
uchar *const output_0__input__0 = (uchar*) (Shared+256256);  // explode_Split_output_output_0 > Sobel_0_input size:= 26048*uchar
uchar *const output_26048__input__0 = (uchar*) (Shared+282304);  // explode_Split_output_output_26048 > Sobel_1_input size:= 26048*uchar
uchar *const output_52096__input__0 = (uchar*) (Shared+308352);  // explode_Split_output_output_52096 > Sobel_2_input size:= 26048*uchar
uchar *const output_78144__input__0 = (uchar*) (Shared+334400);  // explode_Split_output_output_78144 > Sobel_3_input size:= 26048*uchar
uchar *const output__input_0__0 = (uchar*) (Shared+360448);  // Sobel_0_output > implode_Merge_input_input_0 size:= 26048*uchar
uchar *const output__input_52096__0 = (uchar*) (Shared+386496);  // Sobel_2_output > implode_Merge_input_input_52096 size:= 26048*uchar
uchar *const output__input_26048__0 = (uchar*) (Shared+412544);  // Sobel_1_output > implode_Merge_input_input_26048 size:= 26048*uchar
uchar *const output__input_78144__0 = (uchar*) (Shared+438592);  // Sobel_3_output > implode_Merge_input_input_78144 size:= 26048*uchar
uchar *const output__input__1 = (uchar*) (Shared+464640);  // implode_Merge_input_output > Merge_input size:= 104192*uchar
uchar *const output__y__0 = (uchar*) (Shared+568832);  // Merge_output > display_y size:= 101376*uchar

void *computationThread_Core0(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Initialisation(s)
	initReadYUV(352/*width*/,288/*height*/); // Read_YUV
	//yuvDisplayInit(0/*id*/,352/*width*/,288/*height*/); // display

	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		readYUV(352/*width*/,288/*height*/,y__input__0,u__u__0,v__v__0); // Read_YUV
		split(4/*nbSlice*/,352/*width*/,288/*height*/,y__input__0,output__input__0); // Split
		// Fork explode_Split_output
		{
			memcpy(output_0__input__0+0, output__input__0+0, 26048*sizeof(uchar));
			memcpy(output_26048__input__0+0, output__input__0+26048, 26048*sizeof(uchar));
			memcpy(output_52096__input__0+0, output__input__0+52096, 26048*sizeof(uchar));
			memcpy(output_78144__input__0+0, output__input__0+78144, 26048*sizeof(uchar));
		}
		sendStart(0, 1); // Core0 > Core1: explode_Split_output__Sobel___1
		sendEnd(); // Core0 > Core1: explode_Split_output__Sobel___1
		sendStart(0, 1); // Core0 > Core1: explode_Split_output__Sobel___3
		sendEnd(); // Core0 > Core1: explode_Split_output__Sobel___3
//		sobel(352/*width*/,74/*height*/,output_0__input__0,output__input_0__0); // Sobel_0
//		sobel(352/*width*/,74/*height*/,output_52096__input__0,output__input_52096__0); // Sobel_2
#pragma SDS async(1)
		sobel_filter0(output_0__input__0,output__input_0__0,74/*height*/); // Sobel_0
#pragma SDS async(2)
		sobel_filter2(output_52096__input__0,output__input_52096__0,74/*height*/); // Sobel_2

		receiveStart(); // Core1 > Core0: Sobel_1__implode_Merge_input__0
		receiveEnd(1, 0); // Core1 > Core0: Sobel_1__implode_Merge_input__0
		receiveStart(); // Core1 > Core0: Sobel_3__implode_Merge_input__0
		receiveEnd(1, 0); // Core1 > Core0: Sobel_3__implode_Merge_input__0
		// Join implode_Merge_input
		{
			memcpy(output__input__1+0, output__input_0__0+0, 26048*sizeof(uchar));
			memcpy(output__input__1+26048, output__input_26048__0+0, 26048*sizeof(uchar));
			memcpy(output__input__1+52096, output__input_52096__0+0, 26048*sizeof(uchar));
			memcpy(output__input__1+78144, output__input_78144__0+0, 26048*sizeof(uchar));
		}
#pragma SDS wait(1)
#pragma SDS wait(2)
		merge(4/*nbSlice*/,352/*width*/,288/*height*/,output__input__1,output__y__0); // Merge
		//yuvDisplay(0/*id*/,output__y__0,u__u__0,v__v__0); // display
		dummy(0/*id*/,output__y__0,u__u__0,v__v__0); // display
	}
	return NULL;
}

